language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: dMkcqZfP+xKrrTgk77aGFW6tLCGodd/eYC2TRvR/G0qN6Wk8RWGzX2ozfnll4SLD4GXcUMS1dKhiDoiDMCAo0Gnj33o5/zW2yyw2uaJ0ghDQHaTrVFikArJQzTZgsbyLa+NRRmnpfaWVWivAvnGzL+bCXqFBEYeEWaZgEYBiLz/ry2rGWdcLr/acasMiCuMjMpXH3rO5A7CjH6dUvSTmvsU6Yzn5FVsq1Q9tonN75KUt0d2JRXGXG33B7NwxQTg7KJuUpNbqaLlIQUrK8VrLSFtpGPwTaeUAfWqRySAanmSw9bXB4YTY9zEt6cNec25ecs16j/LeR+bFQyftWTG+tpdwP0CJat1kX0M7euyDP2HL+KKLq31Zxd44CS0vjMahKMxKdyw9ltiq7ypuXepABCnhtHaTBoMcZnFSSSNg8oZq7C/Yt0bDX7x+ddtEbeRwGdKhUcwpwJh+o6AfJwz8/OF1EkyzFJvjq5IFM80Z3I5hZM8PLeq+gGxr9PEjojNBct0hBYBwk92eLQKPfI9dfNovUQNn1RgGcE0vBPahpwSS7kUR8YUORuh0baKisluPr6kWKe8fhS4/rGNpCpwNrXw1PKRaqh+Ds1uOMufHukwtREaBWhIbEdJAwyALb72pMtZpr8mGh1cYb7VOOhHWN5z7lwoLyiXGL5qOMioy+uU=
  app: LetsRoll
  on:
    repo: lesleydreyer/LetsRoll
