language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  app: letsroll
  api_key:
    secure: 4reVFVrTz8JYpsci2MtTF0DclNPS+/Msl+5wWJcxoMsrH9105KITyPpbKiS9LsqBoiBakCiAw3zWdcc7JBNY8XSle1JhIZplXAgir19GMToB2q17H3Evjnhlxl6QLPOriIan9lGw1pnYFoMf/lsXO9B+oHkt/Njuf1r1XSM4PsrJ4KYL0rwEH2QNWif8A/UYgVx7SERXK6vXDVNkqNtrtOSlhUK2ZFnMc+ocQMpDOf/UqjRHQpgTBJBkkHkrTIy9aH7tRq5VOGz7DPsk/ZQLD8kBsjCOfAKLIFhfDWNDLYlwdai1QxX0TlqZIaTlOkf+rc/OaJY3BIBDL8J97LLrYOwXrUwRpFujV9rcpZFxlbRqTtr7v0eFcuBAc6/j5YuMnImPwSfazwPYz4EnSnUZryoCWxKIEha78MOaIOAqhw5ugNeD6s3AoSc0bnFaq2kJ9q6NVV8ceIg8UAsxHi19M6NLrpEzvNeXcksEcaGiZo8cYltjDlGYzHZByuZ+IOgi3qPNKDV8O+M9kHhaVRTvBfLGljmb4t2Ipy8x0tgYyQTCzkYkkmDciimbVDsgGt63p9mVj9ZKDfP2wgRSdx98rSY8tTh3aEz5TVCEYaNouCC8Cm03GaT3j7Kbzx96H6k9gHtvVDPLXRG4YBl0x0xRLbASCgOREq1f/pKygsPVCrI=
