language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  app: letsroll
  api_key:
    secure: nzZFsYZvB3VSavvhItxy+C1OGYBovC6ZiI1r5gTG8DNDbD8OCavEBfMD+wXtuQGvVxR4qoQAiADXzaYVbgfQBy5d2Tm0+wAy75iSE34dtJHWFMyC6pFZ3tHvLVmqUmYD85ycTfyu4KIcI2cWqooFUmKSddGoI3X7RWrAdGsc6wURI5kemEUTkf0j2yabD6ey7zZqygo1YaNx+dABq+4OB9SUaYH7g61Tcu1pdOGrN0B5LZ7cmwtnpOrNFxvDO3+mPvmIbgHwDJ2NP4pDAxqqVpuySzUD2NEwZ7n2irRftL4DLDQqQLzkf7SlVPNIkgLbYowkgK7zi7GBWM7drYfNVpiZ31j3Or8z7a/Jcz5Y9oO/NAyH/Kj06VAG6syi8RjZlC2l9zblPEUkUjJ4iM/f3kZSGhRi5DvHXDC7hCr+kmbeOmawJGvXBRjgPNS1bWGpKuneEe3QM48GcUIFwMp568bJrAVccLyxIWa3L+ibKeAOHLawuHh1XeGBUQfOIUYRAwn6bvSZT7TmrtaFDJprKCMl5pEoJKGjt3UyshGA6IsGUP6+OWxkNzNt0/3AQiT5EA7NOxdKTFJm1YoNEOvSTv2Twt5zEZT5vNUC1AErUdwtGKoATDOipDcybba3xuVJ5WvktcmXSi2qPSiiEAWRoGMFdTkgeF+w9ChQipxC6rA=
